title: superjamie.github.io
description: Insert witty tagline
author: superjamie
author_name: Jamie Bainbridge
author_email: jamie.bainbridge@gmail.com
timezone: Australia/Brisbane

show_downloads: false
show_downloads_button: false

gems:
  - jekyll-mentions
  - jekyll-include-cache
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

relative_links:
  enabled:     true
  collections: true

#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
