title: superjamie.github.io
description: Insert witty tagline
author: superjamie
author_name: Jamie Bainbridge
author_email: jamie.bainbridge@gmail.com

show_downloads: false
show_downloads_button: false

gems:
  - jekyll-mentions
plugins:
  - jekyll-remote-theme

relative_links:
  enabled:     true
  collections: true

remote_theme: pages-themes/hacker@v0.2.0
